package mx.gob.renapo.registrocivil.ws.consultaWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaWS",
        targetNamespace = "http://mx.gob.segob.renapo.cirr.controller/",
        wsdlLocation = "http://10.2.150.202:7001/ConsultaWS/ConsultaWS?WSDL")
public class ConsultaWS_Service
    extends Service
{

    private final static URL CONSULTAWS_WSDL_LOCATION;
    private final static WebServiceException CONSULTAWS_EXCEPTION;
    private final static QName CONSULTAWS_QNAME =
            new QName("http://mx.gob.segob.renapo.cirr.controller/", "ConsultaWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.2.150.202:7001/ConsultaWS/ConsultaWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAWS_WSDL_LOCATION = url;
        CONSULTAWS_EXCEPTION = e;
    }

    public ConsultaWS_Service() {
        super(__getWsdlLocation(), CONSULTAWS_QNAME);
    }

    public ConsultaWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAWS_QNAME, features);
    }

    public ConsultaWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAWS_QNAME);
    }

    public ConsultaWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAWS_QNAME, features);
    }

    public ConsultaWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaWS_Service(URL wsdlLocation,
                              QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaWS
     */
    @WebEndpoint(name = "ConsultaWSPort")
    public ConsultaWS getConsultaWSPort() {
        return super.getPort(new QName(
                "http://mx.gob.segob.renapo.cirr.controller/", "ConsultaWSPort"),
                ConsultaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *     Supported features not in the <code>features</code>
     *     parameter will have their default values.
     * @return
     *     returns ConsultaWS
     */
    @WebEndpoint(name = "ConsultaWSPort")
    public ConsultaWS getConsultaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName(
                "http://mx.gob.segob.renapo.cirr.controller/", "ConsultaWSPort"),
                ConsultaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAWS_EXCEPTION!= null) {
            throw CONSULTAWS_EXCEPTION;
        }
        return CONSULTAWS_WSDL_LOCATION;
    }

}
