
package mx.gob.renapo.registrocivil.ws.consultaWS;

import mx.gob.renapo.registrocivil.ws.response.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaWS", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaWS {


    /**
     * 
     * @param hash
     * @param dependencia
     * @param curp
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.NacimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNAcurp", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNAcurp")
    @ResponseWrapper(localName = "consultaNAcurpResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNAcurpResponse")
    public NacimientoRespuesta consultaNAcurp(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "curp", targetNamespace = "")
        String curp,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param sello
     * @param dependencia
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.NacimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNASelloDigital", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNASelloDigital")
    @ResponseWrapper(localName = "consultaNASelloDigitalResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNASelloDigitalResponse")
    public NacimientoRespuesta consultaNASelloDigital(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "sello", targetNamespace = "")
        String sello,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param llave
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.NacimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNALlaveRegistro", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNALlaveRegistro")
    @ResponseWrapper(localName = "consultaNALlaveRegistroResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNALlaveRegistroResponse")
    public NacimientoRespuesta consultaNALlaveRegistro(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "llave", targetNamespace = "")
        String llave,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param nombre
     * @param estado
     * @param hash
     * @param materno
     * @param dependencia
     * @param sexo
     * @param paterno
     * @param fechaNacimiento
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.NacimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNADatos", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNADatos")
    @ResponseWrapper(localName = "consultaNADatosResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNADatosResponse")
    public NacimientoRespuesta consultaNADatos(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "estado", targetNamespace = "")
        Integer estado,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param curp
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.DefuncionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDECurp", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDECurp")
    @ResponseWrapper(localName = "consultaDECurpResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDECurpResponse")
    public DefuncionRespuesta consultaDECurp(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "curp", targetNamespace = "")
        String curp,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param cadena
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.DefuncionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDESelloDigital", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDESelloDigital")
    @ResponseWrapper(localName = "consultaDESelloDigitalResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDESelloDigitalResponse")
    public DefuncionRespuesta consultaDESelloDigital(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param llave
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.DefuncionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDELlaveRegistro", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDELlaveRegistro")
    @ResponseWrapper(localName = "consultaDELlaveRegistroResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDELlaveRegistroResponse")
    public DefuncionRespuesta consultaDELlaveRegistro(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "llave", targetNamespace = "")
        String llave,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param nombre
     * @param estado
     * @param hash
     * @param materno
     * @param dependencia
     * @param sexo
     * @param paterno
     * @param fechaNacimiento
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.DefuncionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDEDatos", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDEDatos")
    @ResponseWrapper(localName = "consultaDEDatosResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaDEDatosResponse")
    public DefuncionRespuesta consultaDEDatos(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "estado", targetNamespace = "")
        Integer estado,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param curp
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.ReconocimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaREcurp", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaREcurp")
    @ResponseWrapper(localName = "consultaREcurpResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaREcurpResponse")
    public ReconocimientoRespuesta consultaREcurp(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "curp", targetNamespace = "")
        String curp,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param cadena
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.ReconocimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaRESelloDigital", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaRESelloDigital")
    @ResponseWrapper(localName = "consultaRESelloDigitalResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaRESelloDigitalResponse")
    public ReconocimientoRespuesta consultaRESelloDigital(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param llave
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.ReconocimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaRELlaveRegistro", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaRELlaveRegistro")
    @ResponseWrapper(localName = "consultaRELlaveRegistroResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaRELlaveRegistroResponse")
    public ReconocimientoRespuesta consultaRELlaveRegistro(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "llave", targetNamespace = "")
        String llave,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param nombre
     * @param estado
     * @param hash
     * @param materno
     * @param dependencia
     * @param sexo
     * @param paterno
     * @param fechaNacimiento
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.ReconocimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaREDatos", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaREDatos")
    @ResponseWrapper(localName = "consultaREDatosResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaREDatosResponse")
    public ReconocimientoRespuesta consultaREDatos(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "estado", targetNamespace = "")
        Integer estado,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param curp
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.AdopcionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaADcurp", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADcurp")
    @ResponseWrapper(localName = "consultaADcurpResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADcurpResponse")
    public AdopcionRespuesta consultaADcurp(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "curp", targetNamespace = "")
        String curp,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param cadena
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.AdopcionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaADSelloDigital", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADSelloDigital")
    @ResponseWrapper(localName = "consultaADSelloDigitalResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADSelloDigitalResponse")
    public AdopcionRespuesta consultaADSelloDigital(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param llave
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.AdopcionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaADLlaveRegistro", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADLlaveRegistro")
    @ResponseWrapper(localName = "consultaADLlaveRegistroResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADLlaveRegistroResponse")
    public AdopcionRespuesta consultaADLlaveRegistro(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "llave", targetNamespace = "")
        String llave,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param nombre
     * @param estado
     * @param hash
     * @param materno
     * @param dependencia
     * @param sexo
     * @param paterno
     * @param fechaNacimiento
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.AdopcionRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaADDatos", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADDatos")
    @ResponseWrapper(localName = "consultaADDatosResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaADDatosResponse")
    public AdopcionRespuesta consultaADDatos(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "estado", targetNamespace = "")
        Integer estado,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param dependencia
     * @param certificado
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.ActoSalud
     */
    @WebMethod(operationName = "ValidaCertificadonacimiento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ValidaCertificadonacimiento", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ValidaCertificadonacimiento")
    @ResponseWrapper(localName = "ValidaCertificadonacimientoResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ValidaCertificadonacimientoResponse")
    public ActoSalud validaCertificadonacimiento(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "certificado", targetNamespace = "")
        String certificado,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param hash
     * @param registro
     * @param dependencia
     * @param certificado
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ReportaCertificadonacimiento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ReportaCertificadonacimiento", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ReportaCertificadonacimiento")
    @ResponseWrapper(localName = "ReportaCertificadonacimientoResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ReportaCertificadonacimientoResponse")
    public Boolean reportaCertificadonacimiento(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "certificado", targetNamespace = "")
        String certificado,
        @WebParam(name = "registro", targetNamespace = "")
        NacimientoVerActo registro,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param nombre
     * @param estado
     * @param hash
     * @param curpMadre
     * @param materno
     * @param curpPadre
     * @param dependencia
     * @param sexo
     * @param paterno
     * @param fechaNacimiento
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validaNacimiento", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ValidaNacimiento")
    @ResponseWrapper(localName = "validaNacimientoResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ValidaNacimientoResponse")
    public Boolean validaNacimiento(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "estado", targetNamespace = "")
        Integer estado,
        @WebParam(name = "curpPadre", targetNamespace = "")
        String curpPadre,
        @WebParam(name = "curpMadre", targetNamespace = "")
        String curpMadre,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @param nombre
     * @param estado
     * @param hash
     * @param materno
     * @param dependencia
     * @param sexo
     * @param curp
     * @param paterno
     * @param llave
     * @param fechaNacimiento
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.NacimientoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNAcompleto", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNAcompleto")
    @ResponseWrapper(localName = "consultaNAcompletoResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.ConsultaNAcompletoResponse")
    public NacimientoRespuesta consultaNAcompleto(
        @WebParam(name = "dependencia", targetNamespace = "")
        String dependencia,
        @WebParam(name = "curp", targetNamespace = "")
        String curp,
        @WebParam(name = "llave", targetNamespace = "")
        String llave,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "paterno", targetNamespace = "")
        String paterno,
        @WebParam(name = "materno", targetNamespace = "")
        String materno,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "estado", targetNamespace = "")
        Integer estado,
        @WebParam(name = "hash", targetNamespace = "")
        String hash);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regresarVersion", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.RegresarVersion")
    @ResponseWrapper(localName = "regresarVersionResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.RegresarVersionResponse")
    public String regresarVersion();

    /**
     * 
     * @param arg0
     * @return
     *     returns mx.gob.renapo.registrocivil.ws.response.DocumentoRespuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regresaActa", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.RegresaActa")
    @ResponseWrapper(localName = "regresaActaResponse", targetNamespace = "http://controller.cirr.renapo.segob.gob.mx/", className = "mx.gob.renapo.registrocivil.ws.response.RegresaActaResponse")
    public DocumentoRespuesta regresaActa(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
